#!/bin/bash

BREW_CURR="$(which -s brew)"
BREW_MISS="brew not found"

if [[ "$BREW_CURR" == "$BREW_MISS" ]] ; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    brew update
fi

brew install abseil freexl json-c libtiff openjdk@17 sdl2 adns frei0r jsoncpp libtool openjpeg shared-mime-info aom fribidi krb5 libunibreak openldap shellcheck apache-arrow fzf lame libunistring openssl@1.1 sip apr gawk leptonica libusb openssl@3 six apr-util gcc libaec libuv opus snappy argon2 gcc@11 libarchive libvidstab orc-tools speex aribb24 gcc@9 libass libvmaf p11-kit sqlite armadillo gd libassuan libvorbis p7zip srt arpack gdal libavif libvpx pandoc starship aspell gdbm libb2 libvterm pandoc-citeproc stoken assimp gdk-pixbuf libbluray libx11 pandoc-crossref superlu augeas geos libcbor libxau pango svt-av1 autoconf gettext libccd libxcb parallel swig automake gflags libcroco libxdmcp pcl szip aws-sdk-cpp gh libdap libxext pcre tcl-tk bash ghostscript libde265 libxml2 pcre2 terminal-notifier bdw-gc giflib libev libxmu pdfgrep tesseract bedops git libevent libxrender perl texi2html bedtools gl2ps libffi libxt php@7.4 texinfo berkeley-db glew libfido2 libyaml picard-tools theora bit glib libgcrypt libzip pinentry thrift boost glog libgeotiff little-cms2 pipx tidy-html5 brotli gmp libgit2 llvm pixman tmux bs-cli gnu-getopt libgpg-error lua pkg-config tokyo-cabinet bzip2 gnu-sed libheif lua@5.1 po4a tree c-ares gnu-tar libice luajit poppler tree-sitter ca-certificates gnupg libidn luarocks poppler-qt5 unbound cairo gnutls libidn2 luv popt unibilium capstone go libkml lz4 portaudio unixodbc certbot gobject-introspection libksba lzo postgresql uriparser cffi gpatch liblerc m4 postgresql@14 utf8cpp cfitsio gpgme liblqr mariadb-connector-c proj utf8proc cjson gradle libmagic mbedtls proj@7 v8@3.15 cmake graphite2 libmd md4c protobuf vde cminpack graphviz libmng minizip pugixml vim cmocka groovy libmpc mkcert pycparser vtk coreutils grpc libnghttp2 mpdecimal pyenv vtk@8.2 curl gsl libogg mpfr pyqt webp dav1d gts libomp mpg123 pyqt@5 wget dbus guile libopenmpt msgpack python-tk@3.9 wmctrl dialog gzip libpcap multimarkdown python@3.10 x264 docbook harfbuzz libpng mutt python@3.11 x265 docbook-xsl hdf5 libpq mysql python@3.7 xerces-c dos2unix heroku libproxy ncurses python@3.8 xmlto double-conversion heroku-node libpthread-stubs neovim python@3.9 xorgproto dpkg highway libraw netcdf qemu xvid duti htop libressl netpbm qhull xz earthly htslib librist nettle qt yarn eigen hunspell librsvg nghttp2 qt@5 yasm epsilon hwloc librttopo node quantlib z exa icu4c libsamplerate npth z3 expat ilmbase libslirp nspr rapidjson zeromq fastqc imagemagick libsm nss rav1e zimg fd imath libsndfile numpy re2 zlib fdk-aac isl libsodium oniguruma readline zsh ffmpeg jasper libsoxr open-mpi rename zstd flac jbig2dec libspatialite openblas ripgrep flann jemalloc libssh openconnect rtmpdump fontconfig jpeg libssh2 opencore-amr rubberband freetds jpeg-turbo libtasn1 openexr ruby freetype jpeg-xl libtermkey openjdk samtools

brew install adoptopenjdk8 gfortran qlcolorcode tcl mactex-no-gui xquartz
