---
output: 
  html_document:
    self_contained: yes
    mode: selfcontained
classoption: landscape
params:
  runID: NULL
  sheetNamePath: NULL
  baseDir: NULL
  knitDir: NULL
  author: "Jonathan Serrano"
---

```{r setup, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
gb <- globalenv(); assign("gb", gb)
defaultRunID <- paste0(basename(getwd()))
if (is.null(params$runID)) {runID <- defaultRunID} else{runID = params$runID}
stopifnot(!is.null(runID)); assign("runID", runID, envir = gb); gb$runID <- runID
defaultBaseDir = file.path(fs::path_home(), "Desktop", runID)
defaultRunPath = file.path("/Volumes/CBioinformatics/Methylation/Clinical_Runs", runID)

# Check if baseDir provided else use Desktop
if (is.null(params$baseDir)) {baseDir = defaultBaseDir} else{baseDir <- paste0(params$baseDir)}
# Check if knitDir is provided else use Clinical_Runs folder
if(is.null(params$knitDir)){runPath <- defaultRunPath}else{runPath <- params$knitDir}
gb$runPath <- runPath
# Check if sheetNamePath provided else use Desktop to look for samplesheet pattern
if (is.null(params$sheetNamePath)) {
    sheetNamePath <- list.files(baseDir, "_samplesheet.csv", full.names = T)
    if (length(sheetNamePath) > 1) {warning(">1 samplesheet in the folder")}
    sheetNamePath <- sheetNamePath[1]
} else{sheetNamePath = params$sheetNamePath}


system(paste("cd", runPath))
knitr::opts_knit$set(runPath) # rprojroot::find_rstudio_root_file()
knitr::opts_knit$set(root.dir=runPath)
message("\nUsing the following output Directory:\n", baseDir)
message("\nUsing the following Knit Directory:\n", runPath)

if (length(sheetNamePath) == 0) {
    warning("No samplesheet found:\n", baseDir)
    samSheetDir <- dir(getwd(), "samplesheet.csv", full.names = T)
    sheetName <- paste0(runID, "_samplesheet.csv")
    newOutPath <- file.path(fs::path_home(), "Desktop", runID, sheetName)
    fs::file_copy(path = samSheetDir, new_path = newOutPath)
    sheetNamePath <- file.path(baseDir, sheetName)
}

if (is.na(sheetNamePath)) {
    sheetNamePath <- dir(getwd(), "samplesheet.csv", full.names = T)
}

message(paste0("Sample sheet name is: ", sheetNamePath))
fixerrors <- read.csv(sheetNamePath, strip.white = T)

if(!dir.exists(baseDir)){baseDir <- getwd()}

targets <- minfi::read.metharray.sheet(baseDir, "samplesheet.csv")

# Checks here if you have odd number of arrays used in makeLabels function
if (nrow(fixerrors) < 8) {
    warning("Less than 8 samples are run, disabling BiocParallel")
    totNum <- 1
} else{
    totNum <- nrow(fixerrors) / 8 # total arrays for biocParrallel workers
}

basePaths <- file.path(runPath, fixerrors$SentrixID_Pos)
fixerrors$Basename <- basePaths
gb$fixerrors <- fixerrors
targets$basenames <- basePaths # path/to/idat/files
wsDate <- fixerrors$Date[1] #format(Sys.time(), '%d %B, %Y')
redCsv <- file.path(fs::path_home(),"Desktop", gb$runID, paste0(gb$runID,"_Redcap.csv"))

if (!file.exists(redCsv)) {
    warning(paste0("File not found - ", redCsv))
    warning("Classifier Summary Table will not generate without _Redcap.csv file")
}

titleName <- paste("Methylation Assay QC for Batch", runID) #heading 1
fileName <- paste0(runID, "_QC.html") # output file name
pSubTitle <- 'Clinical Methylation Run' # subtitle
summarName <- paste("Classifier Report Summary for", runID) # summary table heading

pkgs <-
    c(
        "knitr",
        "kableExtra",
        "magick",
        "webshot",
        "plyr",
        "ggplot2",
        "reshape2",
        "data.table",
        "DT",
        "plotly",
        "MethylAid",
        "minfi",
        "scales",
        "htmltools",
        "IlluminaHumanMethylation450kmanifest",
        "IlluminaHumanMethylationEPICmanifest",
        "IlluminaHumanMethylationEPICanno.ilm10b4.hg19",
        "Biobase",
        "RColorBrewer",
        "limma",
        "ggfortify",
        "Rtsne",
        "qdapTools",
        "gplots",
        "readxl",
        "stringr",
        "ggrepel",
        "Polychrome",
        "tinytex",
        "gridExtra",
        "rmarkdown",
        "BiocParallel",
        "pals",
        "grid",
        "grDevices",
        "magrittr",
        "dplyr"
    )

if(!require("librarian")){
    install.packages("librarian", dependencies=T, verbose=T, Ncpus = 4, quiet=T)}
librarian::shelf(pkgs, ask=F)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(global.par = TRUE, ask = F)
grDevices::devAskNewPage(ask = F)
R.utils::setOption("device.ask.default", FALSE)

gitPath="https://raw.githubusercontent.com/NYU-Molecular-Pathology/Methylation/main/R/Report-Scripts"
htmltools::includeCSS(file.path(gitPath,"QC-Style.html"))
```

```{css, echo = FALSE}
@page {
  size: 11in 8.5in; 
}
@media only screen {
 html {
    font-size: 12px;
  }
  :root {
    --base-font-size: 12px;
  }
}
```

---
title: "`r titleName`"
subtitle: "`r pSubTitle`"
author: "`r paste0(params$author)`"
date: "`r paste0(wsDate)`"
always_allow_html: yes
papersize: a4
linestretch: 1.2
fontsize: 10pt
geometry:
- top=2mm
- left=2mm
- right=2mm
- bottom=2mm
classoption:
- a4paper
- landscape
---

```{r, label = "Margin Params", results='hide', echo=FALSE}
par(mar = c(8, 8, 0, 0)) #it's important to have that in a separate chunk
``` 

```{r BioCParallel, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results='hide'}
library("ggplot2")

# Set Parallel Parameters
mcc = parallel::detectCores()/2
BiocParallel::register(BiocParallel::MulticoreParam(mcc))
mcParam <- BiocParallel::MulticoreParam(workers = mcc, progressbar = T)
fixerrors <- as.data.frame(gb$fixerrors)

# MethylAid Summarize
sdata <- suppressWarnings(
    MethylAid::summarize(
        fixerrors,
        verbose = T,
        batchSize = 8,
        force = TRUE,
        BPPARAM = mcParam
    )
)

qcProbes = list(
    BSI = "^BISULFITE CONVERSION I$",
    BSII = "^BISULFITE CONVERSION II$",
    EC = "^EXTENSION$",
    SPI = "^SPECIFICITY I$",
    HYB = "^HYBRIDIZATION$",
    NP = "^NON-POLYMORPHIC$",
    SPII = "^SPECIFICITY II$",
    TR = "^TARGET REMOVAL$",
    SC = "^STAINING$",
    NC = "^NEGATIVE$"
)

## MU data --------------------------------------
rotateData <- function(data, columns) {
    data[, columns] <- 
        c(0.5 * (data[, columns[1]] + data[, columns[2]]), data[, columns[1]] - data[, columns[2]])
    return(data)
}

## Subset Custom Data --------------------------------------
GetNewDt <- function(data_final, cutoff){
  dataList <- list(final_data = data_final)
  names(dataList) <- c("final_data")
  return(dataList)
}

## Get MU Data & Colors --------------------------------------
MU <- log2(t(sdata@MU)); targets <- sdata@targets; d <- sdata@plotdata
data_rotated <- rotateData(
    merge(MU, targets, by = "row.names"), columns = c("Methylated", "Unmethylated")
    )
data_rotated$x = data_rotated[,2]; data_rotated$y = data_rotated[,3]
MUvals <- GetNewDt(data_final = data_rotated, cutoff = 9)
```

```{r Plot parameters, echo=FALSE, message=FALSE, warning=FALSE, results='hide', paged.print=FALSE}
# FUN: Increases vertical spacing between legend keys
draw_key_polygon3 <- function(data, params, size) {
    lwd <- min(data$size, min(size) / 4)
    grid::rectGrob(
        width = grid::unit(1.5, "npc"),
        height = grid::unit(1.5, "npc"),
        gp = grid::gpar(
            col = data$colour,
            fill = scales::alpha(data$fill, data$alpha),
            lty = data$linetype,
            lwd = lwd * .pt,
            linejoin = "mitre"
        )
    )
}
# register new key drawing fun, global & persistent during R session
GeomBar$draw_key = draw_key_polygon3
set.seed(123)
plot.colours <- glasbey()[1:(length(MUvals$final_data$Sample_Name))]

## Generate Plot labels  ------------------
makeLabels <- function(totNum, xName, yName, plotName, thePlot) {
    legendLabel <- thePlot + xlab(xName) + ylab(yName) + ggtitle(plotName) + 
        theme(
            plot.background = element_blank(),
            legend.title = element_text(size = 12),
            legend.text = element_text(size = 10),
            legend.key = element_rect(size = 2),
            axis.title = element_text(size = 14),
            legend.direction = "horizontal", 
            legend.position = "bottom",
            axis.text.x = element_text(size = 14),
            axis.text.y = element_text(size = 14),
            plot.margin = grid::unit(c(1, 1, 1, 1), 'cm'),
            legend.spacing.x = unit(0.20, 'cm'),
            legend.spacing.y = unit(0.65, 'cm'),
            legend.spacing = unit(0.20, 'cm'),
            plot.title = element_text(color = "navy", size = 26, face = "bold"),
            plot.subtitle = element_text(color = "black", size = 12),
            plot.caption = element_text(color = "darkgreen",face = "italic",size = 12)
            ) +
        labs(label = "", color = "") +
        guides(colour = guide_legend(
            title = "Samples",
            override.aes = list(fill = NA, shape = 19),
            byrow = TRUE, ncol = 9)
            ) + coord_cartesian(clip = 'off') 
    return(legendLabel)
}
## Generate Plots for Probes --------------------------------------
plotParams <- function(totNum, dParam, xincept, yincept) {
    dParam = dParam$final_data
    dParam$Sample_Name = paste(dParam$Sample_Name, dParam$MP_num, sep = "\n")
    plot.colours <- glasbey()[1:(length(dParam$x))]
    thePlot <-
        ggplot(
            dParam,
            aes(
                x = dParam[, 2],
                y = dParam[, 3],
                color = dParam$Sample_Name,
                label = dParam$Sample_Name
            ),
            show.legend = F
        ) +
        scale_color_manual(values = plot.colours) +
        geom_point(shape = 19,
                   size = 5,
                   alpha = 0.8) +
        guides(color = guide_legend(nrow = totNum)) + theme_bw() +
        guides(color = guide_legend(ncol = 8)) +
        scale_fill_manual(values = plot.colours) 
  
  if (yincept == 0){
      thePlot <- thePlot + ggrepel::geom_label_repel(
          aes(
              label = dParam$Sample_Name,
              size = 3,
              fill = dParam$Sample_Name,
              colour = scales::alpha(c("black"), 1.0)
          ),
          fontface = 'bold',
          colour = scales::alpha(c("black"), 1.0),
          alpha = 0.50,
          show.legend = F,
          segment.alpha = 0.30,
          segment.size = 0.75,
          direction = "both",
          max.overlaps = Inf,
          min.segment.length = 0.015,
          color = "black",
          label.size = 0.4,
          size = 3,
          nudge_x = ifelse(thePlot$data$x > mean(thePlot$data$x), -0.15, 0),
          nudge_y = ifelse(thePlot$data$y > mean(thePlot$data$y), -0.05, 0),
          point.padding = unit(0.25, "lines"),
          label.r = unit(0.5, "lines"),
          force = 12,
          max.iter = 10000
      )
      
      thePlot <- thePlot +
          geom_vline(xintercept = xincept, linetype = 'dashed', colour = "red") +
          coord_cartesian(clip="off") +
          expand_limits(x=min(dParam[,2]), y=max(dParam[,3])*0.25) +
          guides(fill = guide_legend(show.legend = F)) + 
          theme(legend.position = "none") + 
          scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
          scale_y_continuous(breaks = scales::pretty_breaks(n = 10))
    }
  if (yincept != 0) {
      samlab <- c(str_replace(dParam$Sample_Name, c("\n"), "_"))
      thePlot <- thePlot +
          geom_hline(yintercept = yincept,
                     linetype = 'dashed',
                     colour = "red") +
          annotate(
              "text",
              x = dParam[, 2],
              y = (dParam[, 3]) - 0.0075,
              label = samlab,
              angle = 90,
              size = 3
          ) +
          scale_x_continuous(breaks = scales::pretty_breaks()) +
          guides(fill = guide_legend(show.legend = F)) +
          theme(legend.position = "none")
      }
  return(thePlot)
}

```

```{r data Functions, echo=FALSE, message=FALSE, warning=FALSE, results='hide', paged.print=FALSE}
## Get Plot Specific Probes --------------------------------------
getProbes <- function(probeName){d <- sdata@plotdata; d <- d[grepl(qcProbes[probeName], d$Type), ]
return(d)
}

## Merges Dataframe Values --------------------------------------
mergeDF <- function(df, tg) {
	mdf <- merge(df,tg,by = "row.names",suffixes = c("", ".y"))
	return(mdf)
}

## Get Data Values for Plot --------------------------------------
getData <- function(theD, exGrn, exRed, cutoff){
	dGrn <- theD[(exGrn), c(1:5, 7)]
	x <- tapply((dGrn$IntGrn), dGrn$Samples, mean)
	is.na(x) <- !is.finite(x)
	dRed <- theD[as.array(exRed), c(1:6)]
	df <- data.frame(x, y = tapply(dRed$IntRed, dRed$Samples, mean))
	mdf <- mergeDF(df,tg=targets)
	plot_data <- rotateData(mdf,columns = c("x", "y"))
	fdt <- plot_data; ott <- subset(plot_data, plot_data$x <= cutoff)
	return(list(final_data = fdt,outlier = ott))
}

get.hc.dat <- function() {
	d <- getProbes("HYB")
	d <- d[order(d$Samples),]
	hiD <- grepl("High", d$ExtendedType)
	loD <- grepl("Low", d$ExtendedType)
	x <- 0.5 * (d$IntGrn[hiD] + d$IntGrn[loD])
	y <- d$IntGrn[hiD] - d$IntGrn[loD]
	df <- data.frame(x = x, y = y, row.names = d$Samples[hiD])
	mdf <- mergeDF(df,tg = targets)
	return(mdf)
}

get.bs.dat <- function() {
	bsD = getProbes(probeName = "BSI")
	BSvals <- getData(theD = bsD, exGrn = grepl("C1|C2|C3", bsD$ExtendedType),
	                  exRed = grepl("C4|C5|C6", bsD$ExtendedType), cutoff = 10)
	return(BSvals)
}

get.op.dat <- function() {
	newD <- getProbes(probeName = "NP")
	OPvals <- getData(theD = newD, exGrn = newD$ExtendedType %in% c("NP (C)", "NP (G)"), 
					  exRed = newD$ExtendedType %in% c("NP (A)", "NP (T)"), cutoff = 11)
	return(OPvals)
}

swm <- function(funObj){return(suppressMessages(suppressWarnings(funObj)))}
```

```{r Plot Getter, echo=FALSE, message=FALSE, warning=FALSE, results='hide', paged.print=FALSE}
## Plot Names --------------------------------------
pltNames <- c(
    "Signal Intensity QC- Checks Raw signal quality (*MU > 9* is Passing)",
    "Biological Positive Control- Overall Amplification (*SBPC > 11* is Passing)",
    "Bisulfite Conversion Control- Zymo Kit Performance (*BS > 10* is Passing)",
    "Hybridization Control QC - Checks Probe Binding (*SHC > 12.75* is Passing)",
    "Negative Control QC - Checks negative probes above background \n(*Pvalue > 0.95* is Passing)"
    )

## MU Plot --------------------------------------
dat.mu <- swm(GetNewDt(data_rotated, cutoff = 9))
plotMU <- swm(plotParams(totNum, dParam = dat.mu, xincept = 9, yincept = 0))
plotMU <- swm(makeLabels(totNum, plotName = paste0(pltNames[1]),
                         xName = "Log2 sqrt(M*U)", yName = "Log2 (M/U)", thePlot = plotMU))

## Plot OP Sample Dependent QC ------------------------------------
dat.op <- get.op.dat()
plotOP <- swm(plotParams(totNum, dParam = dat.op, xincept = 11, yincept = 0))
plotOP <- swm(makeLabels(totNum, plotName = paste0(pltNames[2]),
                         xName = "log2 sqrt(R*G)", yName = "log2 (R/G)", thePlot = plotOP))

## Plot BS Biological Control --------------------------------------
dat.bs <- get.bs.dat()
plotBS <- swm(plotParams(totNum, dParam = dat.bs, xincept = 10, yincept = 0))
plotBS <- swm(makeLabels(totNum, plotName = paste0(pltNames[3]),
                         xName = "log2 sqrt(R*G)", yName = "log2 (R/G)", thePlot = plotBS))

##Plot HC Hybridization Control--------------------------------------
dat.hc <- get.hc.dat()
plotHC <- swm(plotParams(totNum, dParam = GetNewDt(dat.hc, cutoff = 12.75), xincept = 12.75, yincept = 0))
plotHC <- swm(makeLabels(totNum, plotName = paste0(pltNames[4]),
                         xName = "log2 sqrt(H*L)", yName = "log2 (H/L)", thePlot = plotHC))

## Plot DP --------------------------------------
df <- data.frame(x=1:length(sdata@DPfreq), y=sdata@DPfreq, row.names=names(sdata@DPfreq))
dat.dp <- mergeDF(df, tg=targets)
plotDP <- swm(plotParams(totNum, dParam = GetNewDt(dat.dp, cutoff = 0.95),
                         xincept = 0, yincept = 0.95))
plotDP <- swm(makeLabels(totNum, plotName = paste0(pltNames[5]),
                         xName = "Samples", yName = "Pvalue", thePlot = plotDP))
cat("\n\nPage 1 of 8")
```

```{r "Signal Intensity QC", echo=FALSE, error=FALSE, fig.align="left",  fig.margin=TRUE,  message=FALSE, warning=FALSE,  results='hide', fig.width=14.8, fig.height=9.6}
pltCapRUN <- paste(targets$RunID[1])
pltCap <- paste(pltCapRUN, "Page 2 of 8")
pmu <- plotMU + ggplot2::labs(
    subtitle = "Median methylated vs unmethylated log2 intensity plot checks for the raw signal quality per sample. For each CpG site,\nmethylated and unmethylated measurements are produced. The measure of relative methylation levels depend on these signal intensities.\nSamples falling **above threshold (MU > 9) pass QC** and anything below the threshold are considered QC Failed samples.\n", caption = pltCap)
failedMU <- plotMU$data$x <= 9
failedMU <- plotMU$data$MP_num[failedMU]
```

```{r "Signal Intensity QC2", echo=FALSE, warning=FALSE, message=FALSE, fig.align="left", fig.margin=TRUE, results='hide', fig.width=14.8, fig.height=9.6}
plotMU2 <- pmu 
```

```{r "Signal Intensity & Biological Positive Plot", echo=FALSE, warning=FALSE, fig.align="left", message=FALSE, fig.margin=TRUE, fig.width=14.8, fig.height=9.6}
plotMU2 + ggplot2::theme(plot.title = ggplot2::element_text(color = "navy", size = 26, face = "bold"))
pltCap <- paste(pltCapRUN, "Page 3 of 8")
plotOP + ggplot2::labs(subtitle ="Sample biological positive control is assessed based on Non-polymorphic (NP) control probes. NP controls are used to test the overall performance of assay from amplification to detection.\nSamples falling **above threshold (SBPC > 11) pass** this QC and anything below the threshold are considered bad samples.\n", caption = pltCap)
failedOP <- plotOP$data$x <= 11; failedOP <- plotOP$data$MP_num[failedOP]
```

```{r "Bisulfite Conversion", echo=FALSE, warning=FALSE, message=FALSE, fig.align="left", fig.margin=TRUE, fig.width=14.8, fig.height=9.6}
pltCap <- paste(pltCapRUN, "Page 4 of 8")
plotBS + ggplot2::labs(subtitle = "Bisulfite conversion quality is assessed based on Bisulfite Conversion I (BSI) control probes. BSI control probes use Infinium I probe design to monitor efficiency of bisulfite conversion.\nSamples falling **above threshold (BS > 10) pass** this QC and anything below the threshold are considered bad samples.\n", caption = pltCap)
failedBS <- plotBS$data$x <= 10
failedBS <- plotBS$data$MP_num[failedBS]
```

```{r "Sample hybridization Plot", echo=FALSE,  fig.margin=TRUE,  warning=FALSE, fig.align="left", message=FALSE, fig.width=14.8, fig.height=9.6}
pltCap <- paste(pltCapRUN, "Page 5 of 8")
plotHC + ggplot2::labs(subtitle = "Sample hybridization is assessed based on Hybridization control (HC) probes.\nHC probes test the overall performance of the entire assay using synthetic targets instead of amplified DNA.\n**Samples falling above threshold (SHC > 12.75) pass this QC** and anything below the threshold are considered QC Failed samples.",
caption = pltCap)

failedHC <- plotHC$data$x <= 12.75
failedHC <- plotHC$data$MP_num[failedHC]
```

```{r "Sample negative control Plot", fig.margin=TRUE,  echo=FALSE, warning=FALSE, fig.align="left", message=FALSE, fig.width=14.8, fig.height=9.6}
pltCap <- paste(pltCapRUN, "Page 6 of 8")
plotDP + ggplot2::labs(subtitle = "Sample negative control is assessed based on negative control (NC) probes. NC are randomly permuted sequences that should not hybridize to DNA template.\nThe mean signal of these probes defines the background of the system.\nTo be considered as passing this QC, **less than 95%** of probes should be above the background signal.", 
                       caption = pltCap)
failedDP <- plotDP$data$y <= 0.95
failedDP <- plotDP$data$MP_num[failedDP]
```
<hr class="solid"><h2>`r I(as.character(summarName))`</h2>

<div style="align:left;margin-right:auto;margin-left:0px;font-size:10pt;width:850px">
```{r label="Summary Table", fig.align="left", message=FALSE, echo=FALSE, warning=FALSE}
summaryFail <- NULL
runID <- gb$runID #paste(targets$RunID[1])
if (is.null(runID)) {runID = paste0(basename(getwd()))}
redCsv <- file.path(fs::path_home(),"Desktop",runID, paste0(runID,"_Redcap.csv"))
if(!file.exists(redCsv)){knitr::knit_exit()}
mnpOutTb <- as.data.frame(read.csv(redCsv, strip.white = T))

tableHeader <-
    c(
        "RD-number",
        "B-Number",
        "TM-number",
        "Methylation Class",
        "Classifier Score",
        "Subgroup",
        "Subscore",
        "MGMT Status"
    )

genSumFail <- function(failPlot, failTex, sf = summaryFail) {
    ftx = paste("<h4>The following samples **Failed", failTex, "QC:**</h4>")
    if (length(failPlot) > 0) {
        sf <- paste(sf, paste(ftx, paste0(failPlot, "</li>\n"), sep = "\n<li>"))
    }
    return(sf)
}

summaryFail <- genSumFail(failedMU, "Signal intensity")
summaryFail <- genSumFail(failedOP, "Positive Control")
summaryFail <- genSumFail(failedBS, "Bisulfite Conversion")
summaryFail <- genSumFail(failedHC, "Probe Hybridization")
summaryFail <- genSumFail(failedDP, "Negative Control")
summaryFail <- paste(summaryFail, sep = "\n", collapse = "</li>\n")

gCol <- ifelse(mnpOutTb$mgmt_status == "methylated", "red", "blue")
gCel <- ifelse(mnpOutTb$classifier_value < 0.90, "red", "green")
bNum =  mnpOutTb$b_number
rNum = mnpOutTb$record_id

tableSum <- mnpOutTb %>% 
	dplyr::mutate(
		classifier_value = cell_spec(classifier_value, "html", color = gCel, bold = T),
		mgmt_status = cell_spec(mgmt_status, "html", color = gCol)) %>% 
    dplyr::select(
        record_id, b_number, tm_number, classifier_score, classifier_value, 
        subgroup, subgroup_score, mgmt_status
        ) %>%
    kable(format = "html", booktabs = T, escape = F,
          linesep = "", align = "c", col.names = tableHeader) %>% 
	kable_styling("striped", position="left") %>%
	row_spec(which(grepl('control',bNum)),bold=T, color="white",background="orange") %>%
	row_spec(which(grepl('low',bNum)), bold=T, color="white",background="salmon") %>%
	row_spec(which(grepl('_',bNum)),bold=T, color="white",background="salmon") %>%
	kable_styling(latex_options="scale_down")

tableSum <- tableSum %>% kable_styling(position="left")
knitr::asis_output(tableSum)
cat("\n\nPage 7 of 8")
```

```{r label="Failed and Control Values", fig.align="left", message=FALSE, echo=FALSE, warning=FALSE}
jb="<h4>The following samples did not classify with a score >0.90:</h4>\n\n"
failText <- paste("", jb, sep = "\n\n")

lowClassVals <- paste0("**",gb$rNum[mnpOutTb$classifier_value < 0.90],"**")
lowValScores <- mnpOutTb$classifier_value[mnpOutTb$classifier_value < 0.90]
lowScoring <-  paste(lowClassVals, lowValScores, sep = ", ")
failedSams <- unlist(lapply(lowScoring, function(x){paste("<li>\n", x,"</li>\n")}))

controlSample <- paste0(mnpOutTb$tm_number[(which(grepl('control', bNum)))])
if(length(controlSample)==0){
    controlSample <- paste0(mnpOutTb$tm_number[(which(grepl('control', rNum)))])
}
controlSample <- paste("PC Control:", paste(controlSample))
```
</div><hr class="solid">
```{r, post_note_two, echo=FALSE, results='asis'}
if(!is.null(controlSample)) {
    conSam <- paste0('<p><h3 style="color:#3CB371">', controlSample, "</h3></p>")
    cat(conSam, sep = "\n\n")
}
```
<div>

## QC Summary

```{r, post_note, echo=FALSE, results='asis', out.width="65%"}
cat('<p class="comment" style="width:65%;"><ul>')
if (!is.null(summaryFail) & summaryFail !="") {
 	cat(summaryFail, sep = "\n\n")
} else {cat("All samples **Passed each QC Critera**", sep = "\n\n")}
cat('</ul>')
```

## Classifier Scores Summary
<ul class="scrs">
```{r, post_note2, echo=FALSE, results='asis', out.width="65%"}
if (length(failedSams)>0) {
	cat(failText,sep="\n\n");cat(failedSams,sep="");cat("", sep="\n\n")
}else{cat("All samples classified with positive matches", sep = "\n\n")}
htmltools::includeHTML(file.path(gitPath,"QC-Style.html"))
```
</ul>
</p>

<p class="mnpnote"></p>
<p class="qcnote"></p>

```{r, label="Summary_notes", echo=FALSE, results='asis'}
library("knitr");library("kableExtra");library("dplyr")
xlsmSheet <- file.path(gb$runPath, paste0(runID,".xlsm"))
redCsv <- file.path(fs::path_home(),"Desktop",runID, paste0(runID,"_Redcap.csv"))
columnCss <-
    "border-width:2px;border-style:solid;background-color:rgb(255,250,205);
border-color:rgb(105,105,105);width:900px;"

rwcss <-
    "color:white;text-align:center;font-weight:bold;border-color:rgb(105,105,105);background-color:rgb(139,69,19);"

if(!file.exists(xlsmSheet) | !file.exists(redCsv)){knitr::knit_exit()}

noteData <- as.data.frame(readxl::read_excel(xlsmSheet, 2, "M1:M7", col_types = c("text")), row.names=NULL)
noteData <- noteData[c(!is.na(noteData[, 1]) & noteData[, 1] != 0), 1]  %>% as.data.frame
colnames(noteData) <- "Worksheet Notes"

noteData <- noteData %>%
    kable("html", booktabs = T, escape = F, linesep = "") %>%
    kable_styling("striped", full_width = F, font_size = 16, position = "left") %>%
    column_spec(column = c(1), extra_css = columnCss) %>%
    row_spec(row = 0, font_size = 24, extra_css = rwcss)

noteData <- noteData %>% kable_styling(position="left")
knitr::asis_output(noteData)

cat("\n\nPage 8 of 8")
```
</div>
