```{r set-options, echo=FALSE, cache=FALSE , message=FALSE, warning=FALSE}
gitPath <- "https://raw.githubusercontent.com/NYU-Molecular-Pathology/Methylation/main/R/Report-Scripts"
invisible(devtools::source_url(file.path(gitPath,"SarcTables.R")))
htmltools::includeCSS(file.path(gitPath,"SarcStyle.html"))
```
---
title: "Sarcoma Methylation Report (v12b6)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
```{r, label="Sample Info", error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
Mset <- sarc.v12b6::MNPpreprocessIllumina(RGset)
knitr::asis_output(gb$PlotSuppInfo(RGset, Mset, sampleID))
```
### Sarcoma Methylation Classifier Results
```{r, label="Sample Class", echo=FALSE}
predLi <- gb$GetSarcPred(predRaw = sarc.v12b6::MNPpredict(Mset))
knitr::asis_output(gb$PredTable(predLi))
htmltools::includeHTML(file.path(gitPath, "InterpretKey.html"))
```
#### Predicted Methylation Class Description
<p class="methtab">`r predLi$des`</p><hr class="solid">
```{r, label="Sample Class2", echo=FALSE, size="normalsize"}
knitr::asis_output(gb$PredTopTable(predLi))
htmltools::includeHTML(file.path(gitPath, "SarcRef.html"))
```

